version: '3'
services:
    web:
        build: .
        ports: 
            - 4200:4200
        volumes: 
            - .:/usr/local/app
        environment: 
            - NODE_ENV=dev
        command:
            npm start
         